# Generated by Django 2.1.2 on 2018-11-08 22:38

from django.db import migrations

def create_base_template(apps, schema_editor):
    DocumentTemplate = apps.get_model('document', 'DocumentTemplate')
    template = DocumentTemplate()
    template.save()


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0003_documenttemplate'),
    ]

    operations = [
        migrations.RunPython(create_base_template),
    ]
