# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-04 11:12


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0003_auto_20160104_0329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='comments',
            field=models.TextField(default='{}'),
        ),
    ]
