# Generated by Django 2.1.4 on 2018-12-12 15:00

from django.db import migrations, models
import django.db.models.deletion
import document.models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0004_documenttemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='template',
            field=models.ForeignKey(default=document.models.default_template, on_delete=django.db.models.deletion.CASCADE, to='document.DocumentTemplate'),
        ),
    ]
