# Generated by Django 2.1.2 on 2018-12-02 12:57

from django.db import migrations, models
import django.db.models.deletion
import document.models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0005_auto_20181108_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='template',
            field=models.ForeignKey(blank=True, default=document.models.default_template, on_delete=django.db.models.deletion.CASCADE, to='document.DocumentTemplate'),
        ),
    ]
