# Generated by Django 2.1.2 on 2018-11-11 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0005_document_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttemplate',
            name='export_templates',
            field=models.ManyToManyField(to='document.ExportTemplate'),
        ),
    ]
