# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-30 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0005_auto_20160119_0716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessright',
            name='rights',
            field=models.CharField(choices=[(b'r', b'reader'), (b'w', b'author'), (b'e', b'editor'), (b'c', b'reviewer')], max_length=3),
        ),
    ]
