# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-15 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0007_auto_20160130_0709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessright',
            name='rights',
            field=models.CharField(choices=[('r', 'reader'), ('w', 'author'), ('e', 'editor'), ('c', 'reviewer'), ('o', 'comment_only')], max_length=1),
        ),
    ]
