# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-15 13:49


from django.db import migrations

ACCESS_RIGHT_CONV = {
    'w': 'write',
    'r': 'read',
    'o': 'comment',
    'c': 'review',
    'e': 'edit'
}

def modify_access_rights(apps, schema_editor):
    AccessRight = apps.get_model("document","AccessRight")
    for access_right in AccessRight.objects.all():
        access_right.rights = ACCESS_RIGHT_CONV[access_right.rights]
        access_right.save()

ACCESS_RIGHT_DECONV = {
    'write': 'w',
    'read': 'r',
    'comment': 'o',
    'review': 'c',
    'edit': 'e'
}

def demodify_access_rights(apps, schema_editor):
    AccessRight = apps.get_model("document","AccessRight")
    for access_right in AccessRight.objects.all():
        access_right.rights = ACCESS_RIGHT_DECONV[access_right.rights]
        access_right.save()

class Migration(migrations.Migration):

    dependencies = [
        ('document', '0009_auto_20160515_0847'),
    ]

    operations = [
        migrations.RunPython(modify_access_rights, demodify_access_rights),
    ]
