# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-15 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0010_auto_20160515_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessright',
            name='rights',
            field=models.CharField(choices=[(b'read', b'Reader'), (b'write', b'Writer'), (b'edit', b'Editor'), (b'review', b'Reviewer'), (b'comment', b'Commentator')], max_length=7),
        ),
    ]
