# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 21:16


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0015_auto_20161018_0531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessright',
            name='rights',
            field=models.CharField(choices=[('read', 'Reader'), ('read-without-comments', 'Reader without comment access'), ('write', 'Writer'), ('review', 'Reviewer'), ('comment', 'Commentator'), ('edit', 'Editor')], max_length=21),
        ),
        migrations.AlterField(
            model_name='document',
            name='settings',
            field=models.TextField(default='{"doc_version":1}'),
        ),
    ]
