# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-29 10:44


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0016_auto_20161031_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journal_id', models.PositiveIntegerField(default=0)),
                ('submission_id', models.PositiveIntegerField(default=0)),
                ('version_id', models.PositiveIntegerField(default=0)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document.Document')),
            ],
        ),
    ]
