# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-12 13:44


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0019_auto_20161212_0657'),
    ]

    operations = [
        migrations.AddField(
            model_name='submittedaccessright',
            name='submission_id',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
