# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-12 13:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('document', '0020_submittedaccessright_submission_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='submittedaccessright',
            unique_together=set([('document', 'user', 'submission_id')]),
        ),
    ]
