# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-19 12:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0017_auto_20161217_0320'),
        ('document', '0021_auto_20161212_0746'),
    ]

    operations = [
    ]
