# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-22 11:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0022_merge_20161219_0605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='document',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='submittedaccessright',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='submittedaccessright',
            name='document',
        ),
        migrations.RemoveField(
            model_name='submittedaccessright',
            name='user',
        ),
        migrations.DeleteModel(
            name='submission',
        ),
        migrations.DeleteModel(
            name='SubmittedAccessRight',
        ),
    ]
