# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-04 18:11


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0023_auto_20170122_0525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='settings',
            field=models.TextField(default='{"doc_version":1.2}'),
        ),
    ]
