# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-12 11:23


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0024_auto_20170604_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='settings',
            field=models.TextField(default='{"doc_version":1.3}'),
        ),
    ]
