# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 09:57
from __future__ import unicode_literals
from tornado.escape import json_decode

from django.db import migrations

def extract_doc_version(apps, schema_editor):
    Document = apps.get_model('document', 'Document')
    for doc in Document.objects.all():
        try:
            settings = json_decode(doc.settings)
            doc.doc_version = settings["doc_version"]
        except:
            doc.doc_version = 0 # unsupported version
        doc.save()


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0026_auto_20170810_0956'),
    ]

    operations = [
        migrations.RunPython(extract_doc_version)
    ]
