# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 10:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0027_auto_20170810_0957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='settings',
        ),
    ]
