# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 11:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0028_remove_document_settings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-id']},
        ),
    ]
