# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0029_auto_20170810_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='bibliography',
            field=models.TextField(default='{}'),
        ),
    ]
