# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-07 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0031_auto_20180324_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='listed',
            field=models.BooleanField(default=True),
        ),
    ]
