# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-19 04:50


from django.db import migrations

def uploaders_to_owners(apps, schema_editor):
    Image = apps.get_model("usermedia", "Image")
    for image in Image.objects.all():
        image.owner_id = image.uploader_id
        image.save()

class Migration(migrations.Migration):

    dependencies = [
        ('usermedia', '0003_auto_20160218_2222'),
    ]

    operations = [
        migrations.RunPython(uploaders_to_owners),
    ]
