# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-08 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermedia', '0008_documentimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentimage',
            name='title',
            field=models.CharField(default='', max_length=128),
        ),
    ]
