# Generated by Django 3.1.4 on 2021-04-02 18:48

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_loginas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='about',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='contacts',
            field=models.ManyToManyField(related_name='_userprofile_contacts_+', to='user.UserProfile'),
        ),
    ]
