# Generated by Django 3.1.4 on 2021-04-02 18:49

from django.db import migrations


def teammembers_to_contacts(apps, schema_editor):
    UserProfile = apps.get_model('user', 'UserProfile')
    TeamMember = apps.get_model('user', 'TeamMember')
    team_members = TeamMember.objects.all().iterator()
    for team_member in team_members:
        member = UserProfile.objects.get_or_create(user=team_member.member)[0]
        leader = UserProfile.objects.get_or_create(user=team_member.leader)[0]
        leader.contacts.add(member)
        member.contacts.add(leader)
    TeamMember.objects.all().delete()


def contacts_to_teammembers(apps, schema_editor):
    UserProfile = apps.get_model('user', 'UserProfile')
    TeamMember = apps.get_model('user', 'TeamMember')
    profiles = UserProfile.objects.all().iterator()
    for profile in profiles:
        for contact in profile.contacts.all():
            TeamMember.objects.get_or_create(
                leader=profile.user,
                member=contact.user
            )
        profile.contacts.all().delete()



class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210402_2048'),
    ]

    operations = [
        migrations.RunPython(teammembers_to_contacts, contacts_to_teammembers),
    ]
