# Generated by Django 6.0.4 on 2026-04-26 05:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0012_user_language"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserEncryptionKey",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("public_key", models.TextField()),
                ("encrypted_private_key", models.TextField()),
                ("encrypted_master_key", models.TextField()),
                ("user_salt", models.BinaryField(max_length=16)),
                (
                    "user_iterations",
                    models.PositiveIntegerField(default=600000),
                ),
                ("encrypted_master_key_backup", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="encryption_key",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
