# Generated by Django 6.0.4 on 2026-04-26 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0013_userencryptionkey"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="preferences",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="User preferences (e.g., encryption dialog dismissal)",
            ),
        ),
    ]
