# Generated by Django 6.0.5 on 2026-05-12 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0014_user_preferences"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="language",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ar", "Arabic"),
                    ("bg", "Bulgarian"),
                    ("cs", "Czech"),
                    ("da", "Danish"),
                    ("de", "German"),
                    ("en", "English"),
                    ("es", "Spanish"),
                    ("fr", "French"),
                    ("it", "Italian"),
                    ("ja", "Japanese"),
                    ("ko", "Korean"),
                    ("nb", "Norwegian Bokmål"),
                    ("nl", "Dutch"),
                    ("pl", "Polish"),
                    ("pt-br", "Portuguese (Brazil)"),
                    ("pt-pt", "Portuguese (Portugal)"),
                    ("ru", "Russian"),
                    ("sv", "Swedish"),
                    ("tr", "Turkish"),
                    ("zh-hans", "Chinese (Simplified)"),
                ],
                default=None,
                help_text="Interface language preference",
                max_length=10,
                null=True,
            ),
        ),
    ]
