# Generated by Django 5.2.9 on 2026-04-23 07:44

import django.db.models.deletion
import usermedia.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("document", "0021_document_e2ee_document_e2ee_iterations_and_more"),
        ("usermedia", "0006_auto_20200820_0510"),
    ]

    operations = [
        migrations.CreateModel(
            name="EncryptedDocumentImage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="", max_length=128)),
                (
                    "copyright",
                    models.JSONField(
                        default=usermedia.models.default_copyright
                    ),
                ),
                (
                    "image",
                    models.FileField(
                        upload_to=usermedia.models.get_encrypted_file_path
                    ),
                ),
                ("added", models.DateTimeField(auto_now_add=True)),
                ("checksum", models.BigIntegerField(default=0)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="encrypted_images",
                        to="document.document",
                    ),
                ),
            ],
        ),
    ]
