# Generated by Django 2.2.9 on 2020-02-19 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import document.models
import uuid


class Migration(migrations.Migration):

    replaces = [('document', '0001_squashed_0032_document_listed'), ('document', '0002_auto_20180814_1946'), ('document', '0003_auto_20181115_0926'), ('document', '0004_documenttemplate'), ('document', '0005_document_template'), ('document', '0006_auto_20190118_1342'), ('document', '0007_auto_20190227_2105'), ('document', '0008_documenttemplate_doc_version'), ('document', '0009_documentrevision_doc_version'), ('document', '0008_auto_20190701_0943'), ('document', '0010_merge_20190701_1737'), ('document', '0011_auto_20190701_1744'), ('document', '0012_auto_20190704_1219'), ('document', '0013_auto_20190808_1126'), ('document', '0014_auto_20190811_1204'), ('document', '0015_auto_20190828_1108'), ('document', '0016_auto_20190829_2147'), ('document', '0017_remove_documenttemplate_citation_styles'), ('document', '0018_documenttemplate_import_id'), ('document', '0019_remove_documenttemplate_definition_hash')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('style', '0006_auto_20190809_1757'),
        ('style', '0001_squashed_0002_auto_20151226_1110'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('contents', models.TextField(default='{}')),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
                ('last_diffs', models.TextField(default='[]')),
                ('version', models.PositiveIntegerField(default=0)),
                ('comments', models.TextField(default='{}')),
                ('doc_version', models.DecimalField(decimal_places=1, default=2.3, max_digits=3)),
                ('bibliography', models.TextField(default='{}')),
                ('listed', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='DocumentRevision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('date', models.DateTimeField(auto_now=True)),
                ('file_object', models.FileField(upload_to=document.models.revision_filename)),
                ('file_name', models.CharField(blank=True, default='', max_length=255)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document.Document')),
            ],
        ),
        migrations.CreateModel(
            name='AccessRight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rights', models.CharField(choices=[('read', 'Reader'), ('read-without-comments', 'Reader without comment access'), ('write', 'Writer'), ('write-tracked', 'Write with tracked changes'), ('review', 'Reviewer'), ('comment', 'Commentator'), ('edit', 'Editor')], max_length=21)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document.Document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('document', 'user')},
            },
        ),
        migrations.CreateModel(
            name='ExportTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(blank=True, default='', max_length=255)),
                ('file_type', models.CharField(choices=[('docx', 'Docx'), ('odt', 'ODT')], max_length=5)),
                ('template_file', models.FileField(upload_to='export_template')),
            ],
            options={
                'unique_together': {('file_name', 'file_type')},
            },
        ),
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('definition', models.TextField(default='{}')),
                ('definition_hash', models.CharField(blank=True, default='', max_length=22)),
                ('citation_styles', models.ManyToManyField(to='style.CitationStyle')),
                ('document_styles', models.ManyToManyField(to='style.DocumentStyle')),
                ('export_templates', models.ManyToManyField(blank=True, to='document.ExportTemplate')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='template',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='document.DocumentTemplate'),
        ),
        migrations.AlterField(
            model_name='document',
            name='doc_version',
            field=models.DecimalField(decimal_places=1, default=3.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='accessright',
            name='rights',
            field=models.CharField(choices=[('write', 'Writer'), ('write-tracked', 'Write with tracked changes'), ('comment', 'Commentator'), ('review', 'Reviewer'), ('read', 'Reader'), ('read-without-comments', 'Reader without comment access')], max_length=21),
        ),
        migrations.AddField(
            model_name='documenttemplate',
            name='doc_version',
            field=models.DecimalField(decimal_places=1, default=3.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='documentrevision',
            name='doc_version',
            field=models.DecimalField(decimal_places=1, default=3.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='document',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document.DocumentTemplate'),
        ),
        migrations.CreateModel(
            name='AccessRightInvite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('rights', models.CharField(choices=[('write', 'Writer'), ('write-tracked', 'Write with tracked changes'), ('comment', 'Commentator'), ('review', 'Reviewer'), ('read', 'Reader'), ('read-without-comments', 'Reader without comment access')], max_length=21)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document.Document')),
            ],
        ),
        migrations.AddField(
            model_name='documenttemplate',
            name='added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documenttemplate',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.RemoveField(
            model_name='documenttemplate',
            name='document_styles',
        ),
        migrations.RemoveField(
            model_name='documenttemplate',
            name='export_templates',
        ),
        migrations.DeleteModel(
            name='ExportTemplate',
        ),
        migrations.AlterField(
            model_name='document',
            name='doc_version',
            field=models.DecimalField(decimal_places=1, default=3.1, max_digits=3),
        ),
        migrations.AlterField(
            model_name='documentrevision',
            name='doc_version',
            field=models.DecimalField(decimal_places=1, default=3.1, max_digits=3),
        ),
        migrations.AlterField(
            model_name='documenttemplate',
            name='doc_version',
            field=models.DecimalField(decimal_places=1, default=3.1, max_digits=3),
        ),
        migrations.RemoveField(
            model_name='documenttemplate',
            name='citation_styles',
        ),
        migrations.AddField(
            model_name='documenttemplate',
            name='import_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.RemoveField(
            model_name='documenttemplate',
            name='definition_hash',
        ),
    ]
