# Generated by Django 2.2.4 on 2019-08-28 09:08

from django.db import migrations


def set_citationstyles(apps, schema_editor):
    DocumentTemplate = apps.get_model('document', 'DocumentTemplate')
    for doc_template in DocumentTemplate.objects.all():
         citation_styles = []


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0014_auto_20190811_1204'),
    ]

    operations = [
        migrations.RunPython(set_citationstyles),
    ]
