# Generated by Django 5.2.9 on 2026-03-30 12:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("document", "0019_fidus_3_5"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ShareToken",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.UUIDField(default=uuid.uuid4, unique=True)),
                (
                    "rights",
                    models.CharField(
                        choices=[
                            ("write", "Writer"),
                            ("write-tracked", "Write with tracked changes"),
                            ("comment", "Commentator"),
                            (
                                "review-tracked",
                                "Reviewer who can write with tracked changes",
                            ),
                            ("review", "Reviewer"),
                            ("read", "Reader"),
                            (
                                "read-without-comments",
                                "Reader without comment access",
                            ),
                        ],
                        max_length=21,
                    ),
                ),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "note",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="document.document",
                    ),
                ),
            ],
            options={
                "unique_together": {("document", "rights", "created_by")},
            },
        ),
    ]
