# Generated by Django 5.2.9 on 2026-04-21 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("document", "0020_add_share_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="e2ee",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="document",
            name="e2ee_iterations",
            field=models.PositiveIntegerField(default=600000),
        ),
        migrations.AddField(
            model_name="document",
            name="e2ee_salt",
            field=models.BinaryField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name="document",
            name="e2ee_snapshot_version",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
