# Generated by Django 6.0.4 on 2026-04-26 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("document", "0021_document_e2ee_document_e2ee_iterations_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="title",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="documenttemplate",
            name="title",
            field=models.TextField(blank=True, default=""),
        ),
    ]
