# Generated by Django 6.0.4 on 2026-04-26 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("document", "0022_make_title_textfield"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentEncryptionKey",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("holder_id", models.PositiveIntegerField()),
                ("encrypted_key", models.TextField()),
                (
                    "encrypted_with_master_key",
                    models.BooleanField(default=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="encryption_keys",
                        to="document.document",
                    ),
                ),
                (
                    "holder_type",
                    models.ForeignKey(
                        limit_choices_to=models.Q(
                            models.Q(("app_label", "user"), ("model", "user")),
                            models.Q(
                                ("app_label", "user"), ("model", "userinvite")
                            ),
                            _connector="OR",
                        ),
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "unique_together": {("document", "holder_type", "holder_id")},
            },
        ),
    ]
