# Generated by Django 6.0.4 on 2026-04-26 08:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("document", "0023_documentencryptionkey"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Remove the unique_together constraint first
        migrations.AlterUniqueTogether(
            name="documentencryptionkey",
            unique_together=set(),
        ),
        # Remove old fields
        migrations.RemoveField(
            model_name="documentencryptionkey",
            name="holder_id",
        ),
        migrations.RemoveField(
            model_name="documentencryptionkey",
            name="holder_type",
        ),
        # Add new holder field
        migrations.AddField(
            model_name="documentencryptionkey",
            name="holder",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="document_encryption_keys",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        # Re-create unique_together constraint with new field
        migrations.AlterUniqueTogether(
            name="documentencryptionkey",
            unique_together={("document", "holder")},
        ),
    ]
