# Generated by Django 6.0.4 on 2026-04-26 08:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "document",
            "0024_alter_documentencryptionkey_unique_together_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentencryptionkey",
            name="holder",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="document_encryption_keys",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
