# Generated by Django 6.0.6 on 2026-09-07

import os
import shutil

import document.models
from django.conf import settings
from django.db import migrations, models


def move_revisions_to_app_storage(apps, schema_editor):
    DocumentRevision = apps.get_model("document", "DocumentRevision")
    moved = 0
    missing = 0
    for revision in DocumentRevision.objects.exclude(
        file_object=""
    ).iterator():
        name = revision.file_object.name
        base_name = name.split("/")[-1]
        target_path = os.path.join(settings.APP_STORAGE_ROOT, name)
        legacy_paths = [
            os.path.join(settings.MEDIA_ROOT, name),
            os.path.join(settings.MEDIA_ROOT, "document-revisions", base_name),
        ]
        if os.path.isfile(target_path):
            # Already moved. Clean up any leftover in the old location.
            for legacy_path in legacy_paths:
                if os.path.isfile(legacy_path):
                    os.remove(legacy_path)
            continue
        for legacy_path in legacy_paths:
            if os.path.isfile(legacy_path):
                target_dir = os.path.dirname(target_path)
                if target_dir:
                    os.makedirs(target_dir, exist_ok=True)
                try:
                    os.rename(legacy_path, target_path)
                except OSError:
                    shutil.copyfile(legacy_path, target_path)
                    os.remove(legacy_path)
                moved += 1
                break
        else:
            missing += 1
    if missing:
        print(
            f"\n{missing} document revision file(s) were not found in the "
            "old media folder. The corresponding revisions will not be "
            "downloadable.",
            flush=True,
        )
    legacy_dir = os.path.join(settings.MEDIA_ROOT, "document-revisions")
    try:
        os.rmdir(legacy_dir)
    except OSError:
        # Not empty or already gone: leave it alone.
        pass


class Migration(migrations.Migration):

    dependencies = [
        ("document", "0026_fidus_3_6"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentrevision",
            name="file_object",
            field=models.FileField(
                storage=document.models.create_revision_storage,
                upload_to=document.models.revision_filename,
            ),
        ),
        migrations.RunPython(
            move_revisions_to_app_storage, migrations.RunPython.noop
        ),
    ]
