# Generated by Django 6.0 on 2026-07-18
import json
import os
import zipfile
import tempfile
from decimal import Decimal

from django.db import migrations
from django.core.files import File

OLD_FW_DOCUMENT_VERSION = 3.6
FW_DOCUMENT_VERSION = 3.7

STYLE_MAP = {
    "chicago-note-bibliography": "chicago-notes-bibliography",
    "oxford-university-press-humsoc": "oxford-guide-to-style-notes",
}


def update_doc(node):
    if "attrs" in node:
        attrs = node["attrs"]
        if attrs.get("citationstyle") in STYLE_MAP:
            attrs["citationstyle"] = STYLE_MAP[attrs["citationstyle"]]
        if "citationstyles" in attrs and isinstance(
            attrs["citationstyles"], list
        ):
            attrs["citationstyles"] = [
                STYLE_MAP[s] if s in STYLE_MAP else s
                for s in attrs["citationstyles"]
            ]


def update_document_string(doc_string):
    doc = json.loads(doc_string)
    update_doc(doc)
    return json.dumps(doc)


def update_revision_zip(file_field, file_name):
    tmpfd, tmpname = tempfile.mkstemp()
    os.close(tmpfd)
    with zipfile.ZipFile(file_field.open(), "r") as zin:
        with zipfile.ZipFile(tmpname, "w") as zout:
            zout.comment = zin.comment
            for item in zin.infolist():
                if item.filename == "filetype-version":
                    zout.writestr(item, str(FW_DOCUMENT_VERSION))
                elif item.filename == "document.json":
                    doc_string = zin.read(item.filename)
                    zout.writestr(item, update_document_string(doc_string))
                else:
                    zout.writestr(item, zin.read(item.filename))
    with open(tmpname, "rb") as tmp_file:
        file_field.save(file_name, File(tmp_file))
    os.remove(tmpname)


def downgrade_documents(apps, schema_editor):
    Document = apps.get_model("document", "Document")
    documents = Document.objects.all().iterator()
    for document in documents:
        document.doc_version = Decimal(str(OLD_FW_DOCUMENT_VERSION))
        document.save()


def update_documents(apps, schema_editor):
    Document = apps.get_model("document", "Document")
    documents = Document.objects.all().iterator()
    for document in documents:
        if document.doc_version == Decimal(str(OLD_FW_DOCUMENT_VERSION)):
            update_doc(document.content)
            document.doc_version = FW_DOCUMENT_VERSION
            for field in document._meta.local_fields:
                if field.name == "updated":
                    field.auto_now = False
            document.save()

    DocumentTemplate = apps.get_model("document", "DocumentTemplate")
    templates = DocumentTemplate.objects.all()
    for template in templates:
        if template.doc_version == Decimal(str(OLD_FW_DOCUMENT_VERSION)):
            update_doc(template.content)
            template.doc_version = FW_DOCUMENT_VERSION
            template.save()

    DocumentRevision = apps.get_model("document", "DocumentRevision")
    revisions = DocumentRevision.objects.all()
    for revision in revisions:
        if not revision.file_object:
            revision.delete()
            continue
        if revision.doc_version == Decimal(str(OLD_FW_DOCUMENT_VERSION)):
            update_revision_zip(revision.file_object, revision.file_name)
            revision.doc_version = FW_DOCUMENT_VERSION
            revision.save()


class Migration(migrations.Migration):
    dependencies = [
        ("document", "0026_fidus_3_6"),
    ]
    operations = [
        migrations.RunPython(update_documents, downgrade_documents),
    ]
