# Generated by Django 6.0.5 on 2026-07-18 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("document", "0027_fidus_3_7"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="doc_version",
            field=models.DecimalField(
                decimal_places=1, default=3.7, max_digits=3
            ),
        ),
        migrations.AlterField(
            model_name="documentrevision",
            name="doc_version",
            field=models.DecimalField(
                decimal_places=1, default=3.7, max_digits=3
            ),
        ),
        migrations.AlterField(
            model_name="documenttemplate",
            name="doc_version",
            field=models.DecimalField(
                decimal_places=1, default=3.7, max_digits=3
            ),
        ),
    ]
