# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-13 21:34
from __future__ import unicode_literals

from django.db import migrations

def set_bib_type(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Entry = apps.get_model("bibliography", "Entry")
    for entry in Entry.objects.all():
        entry.bib_type = entry.entry_type.type_name
        entry.save()

class Migration(migrations.Migration):

    dependencies = [
        ('bibliography', '0002_entry_bib_type'),
    ]

    operations = [
        migrations.RunPython(set_bib_type),
    ]
