# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-22 11:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('document', '0023_auto_20170122_0525'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journal_id', models.PositiveIntegerField(default=0)),
                ('submission_id', models.PositiveIntegerField(default=0)),
                ('version_id', models.PositiveIntegerField(default=0)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document.Document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubmittedAccessRight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_id', models.PositiveIntegerField(default=0)),
                ('rights', models.CharField(choices=[(b'read', b'Reader'), (b'read-without-comments', b'Reader without comment access'), (b'write', b'Writer'), (b'review', b'Reviewer'), (b'comment', b'Commentator'), (b'edit', b'Editor')], max_length=21)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document.Document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='submittedaccessright',
            unique_together=set([('document', 'user', 'submission_id')]),
        ),
    ]
