# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-23 10:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ojs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ojs_url', models.CharField(max_length=512)),
                ('ojs_key', models.CharField(max_length=512)),
                ('ojs_jid', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=512)),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='submission',
            name='journal_id',
        ),
        migrations.AlterField(
            model_name='submittedaccessright',
            name='submission_id',
            field=models.PositiveIntegerField(),
        ),
        migrations.AddField(
            model_name='submission',
            name='journal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ojs.Journal'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='journal',
            unique_together=set([('ojs_url', 'ojs_jid')]),
        ),
    ]
