# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-09 15:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ojs', '0003_auto_20170309_0509'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='ojs_identifier',
            new_name='ojs_jid',
        ),
    ]
