# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-22 06:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ojs', '0004_auto_20170309_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissionrevision',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document.Document'),
        ),
    ]
