# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-27 08:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ojs', '0005_auto_20170322_0113'),
    ]

    operations = [
        migrations.CreateModel(
            name='OJSUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=8)),
                ('ojs_jid', models.PositiveIntegerField(default=0)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ojs.Submission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='submissionrevision',
            unique_together=set([]),
        ),
        migrations.AlterUniqueTogether(
            name='ojsuser',
            unique_together=set([('submission', 'ojs_jid')]),
        ),
    ]
