# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-25 05:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ojs', '0005_auto_20170322_0113'),
    ]

    operations = [
        migrations.CreateModel(
            name='OJSUSer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=8)),
                ('ojs_jid', models.PositiveIntegerField(default=0)),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ojs.Journal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together=set([('journal', 'ojs_jid')]),
        ),
        migrations.AlterUniqueTogether(
            name='ojsuser',
            unique_together=set([('journal', 'ojs_jid')]),
        ),
    ]
