# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-03 18:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ojs', '0007_auto_20170402_2000'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='submittedaccessright',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='submittedaccessright',
            name='document',
        ),
        migrations.RemoveField(
            model_name='submittedaccessright',
            name='user',
        ),
        migrations.DeleteModel(
            name='SubmittedAccessRight',
        ),
    ]
