# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-15 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20151226_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookaccessright',
            name='rights',
            field=models.CharField(choices=[(b'r', b'read'), (b'w', b'read/write')], max_length=5),
        ),
    ]
