# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-15 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_auto_20160515_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookaccessright',
            name='rights',
            field=models.CharField(choices=[(b'read', b'Reader'), (b'write', b'Writer')], max_length=5),
        ),
    ]
