import argparse

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "level": "INFO",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
}

parser = argparse.ArgumentParser()
parser.add_argument(
    "--debug-mode", action="store_true", help="Enable debug mode"
)
args, _unknown = parser.parse_known_args()

if args.debug_mode:
    LOGGING["root"]["level"] = "DEBUG"
    LOGGING["handlers"]["console"]["level"] = "DEBUG"

INSTALLED_APPS = [
    "user_template_manager",
]

# Disable axes for testing to reduce console output and avoid lockout issues
REMOVED_APPS = [
    "axes",
]

# Use plain StaticFilesStorage instead of CompressedManifestStaticFilesStorage
# during CI tests.  The manifest storage requires a pre-built staticfiles.json
# (generated by collectstatic), but CI runs setup --no-static which skips it.
# Without this override the ASGI child process crashes when servestatic resolves
# the staticfiles storage during middleware initialization.
STORAGES = {
    "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage"
    },
}
